In these project we are going to build a system that can predict whether an object is either Rock or Mine with SONAR data.For this case we are using Logistic Regression Model for our prediction.

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Data

In [2]:
data=pd.read_csv("C:\python\Datasets\Sonar Data.csv",header=None)

In [3]:
pd.set_option('display.max_columns',None)
data.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9       10      11      12      13      14      15      16      17  \
0  0.2111  0.1609  0.1582  0.2238  0.0645  0.0660  0.2273  0.3100  0.2999   
1  0.2872  0.4918  0.6552  0.6919  0.7797  0.7464  0.9444  1.0000  0.8874   
2  0.6194  0.6333  0.7060  0.5544  0.5320  0.6479  0.6931  0.6759  0.7551   
3  0.1264  0.0881  0.1992  0.0184  0.2261  0.1729  0.2131  0.0693  0.2281   
4  0.4459  0.4152  0.3952  0.4256  0.4135  0.4528  0.5326  0.7306  0.6193   

       18      19      20      21      22      23      24      25      26  \
0  0.5078  0.4797  0.5783  0.5071  0.4328  0.5550  0.6711  0.6415  0.7104   
1  0.8024  0.7818  0.5212  0.4052  0.3957  0.3914  0.3250  0.3200  0.3271   
2  0.8929  0.8619  0.7974  0.6737  0.4293  0.3648  0.5331  0.2413  0.5070   
3  0.4060  0.3973  0.2741  0.3690  0.5556  0.4846  0.3140  0.5334  0.5256   
4  0.2032  0.4636  0.4148  0.4292  0.5730  0.5399  0.3161  0.2285  0.6995   

       27      28      29      30      31      32      33      34      35  \
0  0.8080  0.6791  0.3857  0.1307  0.2604  0.5121  0.7547  0.8537  0.8507   
1  0.2767  0.4423  0.2028  0.3788  0.2947  0.1984  0.2341  0.1306  0.4182   
2  0.8533  0.6036  0.8514  0.8512  0.5045  0.1862  0.2709  0.4232  0.3043   
3  0.2520  0.2090  0.3559  0.6260  0.7340  0.6120  0.3497  0.3953  0.3012   
4  1.0000  0.7262  0.4724  0.5103  0.5459  0.2881  0.0981  0.1951  0.4181   

       36      37      38      39      40      41      42      43      44  \
0  0.6692  0.6097  0.4943  0.2744  0.0510  0.2834  0.2825  0.4256  0.2641   
1  0.3835  0.1057  0.1840  0.1970  0.1674  0.0583  0.1401  0.1628  0.0621   
2  0.6116  0.6756  0.5375  0.4719  0.4647  0.2587  0.2129  0.2222  0.2111   
3  0.5408  0.8814  0.9857  0.9167  0.6121  0.5006  0.3210  0.3202  0.4295   
4  0.4604  0.3217  0.2828  0.2430  0.1979  0.2444  0.1847  0.0841  0.0692   

       45      46      47      48      49      50      51      52      53  \
0  0.1386  0.1051  0.1343  0.0383  0.0324  0.0232  0.0027  0.0065  0.0159   
1  0.0203  0.0530  0.0742  0.0409  0.0061  0.0125  0.0084  0.0089  0.0048   
2  0.0176  0.1348  0.0744  0.0130  0.0106  0.0033  0.0232  0.0166  0.0095   
3  0.3654  0.2655  0.1576  0.0681  0.0294  0.0241  0.0121  0.0036  0.0150   
4  0.0528  0.0357  0.0085  0.0230  0.0046  0.0156  0.0031  0.0054  0.0105   

       54      55      56      57      58      59 60  
0  0.0072  0.0167  0.0180  0.0084  0.0090  0.0032  R  
1  0.0094  0.0191  0.0140  0.0049  0.0052  0.0044  R  
2  0.0180  0.0244  0.0316  0.0164  0.0095  0.0078  R  
3  0.0085  0.0073  0.0050  0.0044  0.0040  0.0117  R  
4  0.0110  0.0015  0.0072  0.0048  0.0107  0.0094  R

## Data Preprocessing

In [4]:
data.shape

(208, 61)

In [5]:
data.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [6]:
data.describe()        # Statistical measure of the data

0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9           10          11  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.121747    0.134799    0.178003    0.208259    0.236013    0.250221   
std      0.061788    0.085152    0.118387    0.134416    0.132705    0.140072   
min      0.003300    0.005500    0.007500    0.011300    0.028900    0.023600   
25%      0.080900    0.080425    0.097025    0.111275    0.129250    0.133475   
50%      0.106950    0.112100    0.152250    0.182400    0.224800    0.249050   
75%      0.154000    0.169600    0.233425    0.268700    0.301650    0.331250   
max      0.372900    0.459000    0.682800    0.710600    0.734200    0.706000   

               12          13          14          15          16          17  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.273305    0.296568    0.320201    0.378487    0.415983    0.452318   
std      0.140962    0.164474    0.205427    0.232650    0.263677    0.261529   
min      0.018400    0.027300    0.003100    0.016200    0.034900    0.037500   
25%      0.166125    0.175175    0.164625    0.196300    0.205850    0.242075   
50%      0.263950    0.281100    0.281700    0.304700    0.308400    0.368300   
75%      0.351250    0.386175    0.452925    0.535725    0.659425    0.679050   
max      0.713100    0.997000    1.000000    0.998800    1.000000    1.000000   

               18          19          20          21          22          23  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.504812    0.563047    0.609060    0.624275    0.646975    0.672654   
std      0.257988    0.262653    0.257818    0.255883    0.250175    0.239116   
min      0.049400    0.065600    0.051200    0.021900    0.056300    0.023900   
25%      0.299075    0.350625    0.399725    0.406925    0.450225    0.540725   
50%      0.434950    0.542500    0.617700    0.664900    0.699700    0.698500   
75%      0.731400    0.809325    0.816975    0.831975    0.848575    0.872175   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               24          25          26          27          28          29  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.675424    0.699866    0.702155    0.694024    0.642074    0.580928   
std      0.244926    0.237228    0.245657    0.237189    0.240250    0.220749   
min      0.024000    0.092100    0.048100    0.028400    0.014400    0.061300   
25%      0.525800    0.544175    0.531900    0.534775    0.463700    0.411400   
50%      0.721100    0.754500    0.745600    0.731900    0.680800    0.607150   
75%      0.873725    0.893800    0.917100    0.900275    0.852125    0.735175   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               30          31          32          33          34          35  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.504475    0.439040    0.417220    0.403233    0.392571    0.384848   
std      0.213992    0.213237    0.206513    0.231242    0.259132    0.264121   
min      0.048200    0.040400    0.047700

In [7]:
data[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

M ---> Mine <br>
R ---> Rock

In [8]:
data.groupby(60).mean()

0         1         2         3         4         5         6   \
60                                                                         
M   0.034989  0.045544  0.050720  0.064768  0.086715  0.111864  0.128359   
R   0.022498  0.030303  0.035951  0.041447  0.062028  0.096224  0.114180   

          7         8         9         10        11        12        13  \
60                                                                         
M   0.149832  0.213492  0.251022  0.289581  0.301459  0.314426  0.320692   
R   0.117596  0.137392  0.159325  0.174713  0.191589  0.226249  0.268963   

          14        15        16        17        18        19        20  \
60                                                                         
M   0.331182  0.380999  0.415007  0.455882  0.538062  0.617941  0.667426   
R   0.307636  0.375611  0.417100  0.448240  0.466762  0.500229  0.542270   

          21        22        23        24        25        26        27  \
60                                                                         
M   0.672325  0.676701  0.689165  0.681204  0.706075  0.714754  0.712269   
R   0.569290  0.612959  0.653761  0.668809  0.692762  0.687737  0.673145   

          28        29        30        31        32       33        34  \
60                                                                        
M   0.650283  0.581796  0.482378  0.428049  0.396577  0.36614  0.337553   
R   0.632680  0.579934  0.529762  0.451619  0.440841  0.44568  0.455530   

          35        36        37        38        39        40        41  \
60                                                                         
M   0.318553  0.317034  0.331608  0.336365  0.305221  0.292594  0.300975   
R   0.460710  0.417330  0.348868  0.313709  0.318057  0.285428  0.252338   

          42        43        44        45        46        47        48  \
60                                                                         
M   0.276883  0.248106  0.245225  0.198804  0.146917  0.110594  0.063708   
R   0.211822  0.175132  0.142312  0.116949  0.094458  0.069488  0.038449   

          49        50        51        52        53        54        55  \
60                                                                         
M   0.022721  0.019352  0.016014  0.011643  0.012185  0.009923  0.008914   
R   0.017796  0.012311  0.010453  0.009640  0.009518  0.008567  0.007430   

          56        57        58        59  
60                                          
M   0.007825  0.009060  0.008695  0.006930  
R   0.007814  0.006677  0.007078  0.006024

The first row represents mean value for Mine in the respective columns and the second row represents mean value for the Rock 
in the respective columns.<br>
The difference of means (between Mine and Rock) is very important . As it is used to predict that the object is either Rock or Mine.

## Divide the data into Dependent and Indenpendent Variable

In [9]:
x=data.iloc[:,:-1].values
x

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [10]:
y=data.iloc[:,-1]

In [11]:
y=y.replace({'R':0,'M':1}).values

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

## Split the data into Training and Testing 

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,stratify=y,random_state=1)

In [15]:
x_train,x_test,y_train,y_test

(array([[0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115],
        [0.021 , 0.0121, 0.0203, ..., 0.0107, 0.0161, 0.0133],
        [0.0305, 0.0363, 0.0214, ..., 0.0042, 0.0055, 0.0021],
        ...,
        [0.0195, 0.0142, 0.0181, ..., 0.0042, 0.0067, 0.0012],
        [0.026 , 0.0192, 0.0254, ..., 0.0008, 0.0044, 0.0077],
        [0.0152, 0.0102, 0.0113, ..., 0.0011, 0.0034, 0.0033]]),
 array([[0.0307, 0.0523, 0.0653, ..., 0.0121, 0.0124, 0.0055],
        [0.0089, 0.0274, 0.0248, ..., 0.0069, 0.006 , 0.0018],
        [0.0208, 0.0186, 0.0131, ..., 0.0019, 0.0049, 0.0023],
        ...,
        [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
        [0.0164, 0.0173, 0.0347, ..., 0.0035, 0.0056, 0.004 ],
        [0.0095, 0.0308, 0.0539, ..., 0.003 , 0.0031, 0.0033]]),
 array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0

## Fit the Logistic Regression model to training data

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
model=LogisticRegression()

In [18]:
model.fit(x_train,y_train)

LogisticRegression()

## Prediction  for Train data

In [19]:
y_pred_train=model.predict(x_train)
y_pred_train

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1], dtype=int64)

## Accuracy on Train Data

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [21]:
acc=accuracy_score(y_train,y_pred_train)*100
acc

83.42245989304813

In [24]:
print(f'Accuracy score for the training data is {acc} %. Which is quite good.')

Accuracy score for the training data is 83.42245989304813 %. Which is quite good.


## Prediction for Test Data

In [25]:
y_pred=model.predict(x_test)

In [26]:
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

array([[1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1]], dtype=int64)

## Accuracy on Test data

In [27]:
acc=accuracy_score(y_test,y_pred)*100
acc

80.95238095238095

In [28]:
print('Accuracy score for the testing data is {} %'.format(acc)) 

Accuracy score for the testing data is 80.95238095238095 %
